[features]
seeds = false
skip-lint = false

[programs.localnet]
calculator = "7MDVqq52Am3UYcdF3N1FyqCBXNRvkJsoBLzhhVA9Vi5d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
